UPDATE KUNDE
SET NAME = 'Finn Jannsen'
WHERE NAME = 'Finn-Frederik Jannsen';

UPDATE PRODUKT
SET PREIS = PREIS * 1.2;


-- Change Prices into Thai Baht

ALTER TABLE PRODUKT 
DROP CONSTRAINT VALIDER_PREIS;

ALTER TABLE PRODUKT
ADD CONSTRAINT VALIDER_PREIS CHECK (Preis >= 0.00 and Preis < (1000.00 * 37.4235)); -- Calculate limit into Thai Baht

UPDATE PRODUKT
SET PREIS = PREIS * 37.4235; -- Calculate prices into Thai Baht

-- Delete customers who didn't order anything

DELETE FROM TELEFONNUMMER
WHERE TELEFONNUMMER.KUNDENNUMMER NOT IN (SELECT BESTELLUNG.KUNDENNUMMER FROM BESTELLUNG);

DELETE FROM MERKLISTE_PRODUKT_BESTEHT
WHERE MERKLISTE_PRODUKT_BESTEHT.KUNDENNUMMER NOT IN (SELECT BESTELLUNG.KUNDENNUMMER FROM BESTELLUNG);

DELETE FROM MERKLISTE
WHERE MERKLISTE.KUNDENNUMMER NOT IN (SELECT BESTELLUNG.KUNDENNUMMER FROM BESTELLUNG);

DELETE FROM KUNDE
WHERE KUNDE.KUNDENNUMMER NOT IN (SELECT BESTELLUNG.KUNDENNUMMER FROM BESTELLUNG);


-- Delete all customers

DELETE FROM TELEFONNUMMER
WHERE TELEFONNUMMER.KUNDENNUMMER IN (SELECT KUNDENNUMMER FROM KUNDE);

DELETE FROM BESTELLUNG_PRODUKT_BESTEHT
WHERE BESTELLNUMMER IN (SELECT BESTELLNUMMER FROM BESTELLUNG);

DELETE FROM BESTELLUNG
WHERE BESTELLUNG.KUNDENNUMMER IN (SELECT KUNDENNUMMER FROM KUNDE);

DELETE FROM MERKLISTE_PRODUKT_BESTEHT
WHERE MERKLISTE_PRODUKT_BESTEHT.KUNDENNUMMER IN (SELECT KUNDENNUMMER FROM KUNDE);

DELETE FROM MERKLISTE
WHERE MERKLISTE.KUNDENNUMMER IN (SELECT KUNDENNUMMER FROM KUNDE);

DELETE FROM KUNDE;


-- Add customers back to the database


INSERT INTO Kunde
VALUES (
    1,
	'Philipp Schwarz',
	'ABC-Straße',
	3,
	'Hamburg'
);

INSERT INTO Kunde
VALUES (
    2,
	'Finn-Frederik Jannsen',
	'CDE-Straße',
	2,
	'Hamburg'
);

INSERT INTO Kunde
VALUES (
    3,
	'Martin Schultz',
	'Am Grünweg',
	74,
	'Hamburg'
);

INSERT INTO Kunde
VALUES (
    4,
	'Otto Wels',
	'Weimarer Straße',
	18,
	'Berlin'
);

INSERT INTO Telefonnummer
VALUES (1, 12345);

INSERT INTO Telefonnummer
VALUES (2, 23456);

INSERT INTO Telefonnummer
VALUES (3, 34567);

INSERT INTO Telefonnummer
VALUES (4, 45678);