UPDATE KUNDE
SET NAME = 'Finn Jannsen'
WHERE NAME = 'Finn-Frederik Jannsen';

UPDATE PRODUKT
SET PREIS = PREIS * 1.2;


-- Change Prices into Thai Baht

ALTER TABLE PRODUKT 
DROP CONSTRAINT VALIDER_PREIS;

ALTER TABLE PRODUKT
ADD CONSTRAINT VALIDER_PREIS CHECK (Preis >= 0.00 and Preis < (1000.00 * 37.4235)); -- Calculate limit into Thai Baht

UPDATE PRODUKT
SET PREIS = PREIS * 37.4235; -- Calculate prices into Thai Baht

-- Delete customers who didn't order anything

DELETE FROM TELEFONNUMMER
WHERE TELEFONNUMMER.KUNDENNUMMER NOT IN (SELECT BESTELLUNG.KUNDENNUMMER FROM BESTELLUNG);

DELETE FROM MERKLISTE_PRODUKT_BESTEHT
WHERE MERKLISTE_PRODUKT_BESTEHT.KUNDENNUMMER NOT IN (SELECT BESTELLUNG.KUNDENNUMMER FROM BESTELLUNG);

DELETE FROM MERKLISTE
WHERE MERKLISTE.KUNDENNUMMER NOT IN (SELECT BESTELLUNG.KUNDENNUMMER FROM BESTELLUNG);

DELETE FROM KUNDE
WHERE KUNDE.KUNDENNUMMER NOT IN (SELECT BESTELLUNG.KUNDENNUMMER FROM BESTELLUNG);


-- Delete all customers

DELETE FROM TELEFONNUMMER
WHERE TELEFONNUMMER.KUNDENNUMMER IN (SELECT KUNDENNUMMER FROM KUNDE);

DELETE FROM BESTELLUNG_PRODUKT_BESTEHT
WHERE BESTELLNUMMER IN (SELECT BESTELLNUMMER FROM BESTELLUNG);

DELETE FROM BESTELLUNG
WHERE BESTELLUNG.KUNDENNUMMER IN (SELECT KUNDENNUMMER FROM KUNDE);

DELETE FROM MERKLISTE_PRODUKT_BESTEHT
WHERE MERKLISTE_PRODUKT_BESTEHT.KUNDENNUMMER IN (SELECT KUNDENNUMMER FROM KUNDE);

DELETE FROM MERKLISTE
WHERE MERKLISTE.KUNDENNUMMER IN (SELECT KUNDENNUMMER FROM KUNDE);

DELETE FROM KUNDE;


-- Add customers back to the database


INSERT INTO Kunde
VALUES (
    1,
	'Philipp Schwarz',
	'ABC-Straße',
	3,
	'Hamburg'
);

INSERT INTO Kunde
VALUES (
    2,
	'Finn-Frederik Jannsen',
	'CDE-Straße',
	2,
	'Hamburg'
);

INSERT INTO Kunde
VALUES (
    3,
	'Martin Schultz',
	'Am Grünweg',
	74,
	'Hamburg'
);

INSERT INTO Kunde
VALUES (
    4,
	'Otto Wels',
	'Weimarer Straße',
	18,
	'Berlin'
);

INSERT INTO Telefonnummer
VALUES (1, 12345);

INSERT INTO Telefonnummer
VALUES (2, 23456);

INSERT INTO Telefonnummer
VALUES (3, 34567);

INSERT INTO Telefonnummer
VALUES (4, 45678);

INSERT INTO Zahlungsart
VALUES (1234);

INSERT INTO Zahlungsart
VALUES (2345);

INSERT INTO Zahlungsart
VALUES (3456);

INSERT INTO Bestellung
VALUES (
    1,
	1,
	1234,
	TO_DATE ('15.05.2018 18:31','DD.MM.YYYY HH24:MI'),
	'Versand'
);

INSERT INTO Bestellung
VALUES (
    2,
	1,
	1234,
	TO_DATE ('15.05.2018 20:31','DD.MM.YYYY HH24:MI'),
	'Versand'
);

INSERT INTO Bestellung
VALUES (
    3,
	2,
	2345,
	TO_DATE ('16.05.2018 02:12','DD.MM.YYYY HH24:MI'),
	'Versand'
);

INSERT INTO Bestellung
VALUES (
    4,
	2,
	2345,
	TO_DATE ('16.05.2018 12:31','DD.MM.YYYY HH24:MI'),
	'Bearbeitung'
);

INSERT INTO Bestellung
VALUES (
    5,
	3,
	3456,
	TO_DATE ('16.05.2018 14:00','DD.MM.YYYY HH24:MI'),
	'Bearbeitung'
);

INSERT INTO Bestellung
VALUES (
    6,
	3,
	3456,
	TO_DATE ('16.05.2018 14:31','DD.MM.YYYY HH24:MI'),
	'Bearbeitung'
);

INSERT INTO Bestellung_Produkt_Besteht
VALUES (1, 1, 1);

INSERT INTO Bestellung_Produkt_Besteht
VALUES (2, 1, 1);

INSERT INTO Bestellung_Produkt_Besteht
VALUES (3, 2, 1);

INSERT INTO Bestellung_Produkt_Besteht
VALUES (4, 2, 2);

INSERT INTO Bestellung_Produkt_Besteht
VALUES (5, 3, 1);

INSERT INTO Bestellung_Produkt_Besteht
VALUES (1, 3, 1);

INSERT INTO Bestellung_Produkt_Besteht
VALUES (2, 4, 1);

INSERT INTO Bestellung_Produkt_Besteht
VALUES (3, 4, 1);

INSERT INTO Bestellung_Produkt_Besteht
VALUES (4, 5, 2);

INSERT INTO Bestellung_Produkt_Besteht
VALUES (5, 5, 1);

INSERT INTO Bestellung_Produkt_Besteht
VALUES (1, 6, 1);

INSERT INTO Bestellung_Produkt_Besteht
VALUES (2, 6, 3);

INSERT INTO Überweisung
VALUES (1234, 'Philipp Schwarz', 778899);

INSERT INTO Überweisung
VALUES (2345, 'Finn-Frederik Jannsen', 667788);

INSERT INTO Kreditkarte
VALUES (3456, 123, '05.12.2020');

-- Restore prices
UPDATE PRODUKT
SET PREIS = PREIS / 31.18625; -- Calculate prices back into Euro and also 20% less

ALTER TABLE PRODUKT 
DROP CONSTRAINT VALIDER_PREIS;

ALTER TABLE PRODUKT
ADD CONSTRAINT VALIDER_PREIS CHECK (Preis >= 0.00 and Preis < 1000.00); -- Calculate limit back into euro